# Generated by Django 6.0.6 on 2026-08-26 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_email', models.BooleanField(default=True)),
                ('recibir_recordatorios', models.BooleanField(default=True)),
                ('eventos_silenciados', models.JSONField(blank=True, default=list)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificacion',
                'verbose_name_plural': 'Preferencias de Notificacion',
                'db_table': 'preferencias_notificacion',
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='clave_dedupe',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviada_por_correo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='error_envio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='evento',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_dedupe', ''), _negated=True), fields=('usuario', 'clave_dedupe'), name='uniq_notificacion_dedupe'),
        ),
        migrations.AddField(
            model_name='preferencianotificacion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
