# Generated by Django 6.0.6 on 2026-08-27 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('retos', '0010_equiporetoacademico_equipo_espejo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_participacion', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Docente'), ('EMPRESA', 'Empresa'), ('JURADO', 'Jurado')], max_length=20)),
                ('codigo_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='retos.reto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados',
                'ordering': ['-emitido_en'],
                'unique_together': {('reto', 'usuario', 'rol_participacion')},
            },
        ),
    ]
