# Generated by Django 6.0.6 on 2026-08-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_normalizar_catalogo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together={('nombre', 'facultad')},
        ),
    ]
