# Generated by Django 6.0.6 on 2026-07-10 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la unidad')),
                ('periodo', models.CharField(max_length=20, verbose_name='Periodo (ej: 2026-2)')),
                ('ciclo', models.CharField(max_length=50, verbose_name='Ciclo / Semestre')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='unidades_estudio/', verbose_name='Archivo (PDF con info completa)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_estudio', to='academico.programa', verbose_name='Programa académico')),
            ],
            options={
                'verbose_name': 'Unidad de Estudio',
                'verbose_name_plural': 'Unidades de Estudio',
                'db_table': 'unidades_estudio',
                'ordering': ['programa', 'ciclo', 'nombre'],
            },
        ),
    ]
