# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Reto',
                'verbose_name_plural': 'Historial de Estados de Reto',
                'db_table': 'historial_estados_reto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IntegracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(blank=True, max_length=140)),
                ('nivel_formacion', models.CharField(blank=True, max_length=120)),
                ('programa_academico', models.CharField(blank=True, max_length=160)),
                ('ecosistema', models.CharField(blank=True, max_length=140)),
                ('alcance', models.TextField(blank=True)),
                ('entregable_esperado', models.CharField(blank=True, max_length=180)),
                ('cronograma_sesiones', models.TextField(blank=True)),
                ('equipo_profesores', models.TextField(blank=True)),
                ('equipo_estudiantes', models.TextField(blank=True)),
                ('expertos_invitados', models.TextField(blank=True)),
                ('requerimientos_empresa', models.TextField(blank=True)),
                ('requerimientos_internos', models.TextField(blank=True)),
                ('espacio_fisico', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integracion academica',
                'verbose_name_plural': 'Integraciones academicas',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reto', 'Reto'), ('hackathon', 'Hackathon')], default='reto', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('nivel_academico', models.CharField(blank=True, max_length=120)),
                ('fecha_inicio_tentativa', models.DateField(blank=True, null=True)),
                ('fecha_fin_tentativa', models.DateField(blank=True, null=True)),
                ('fecha_limite_postulacion', models.DateField(blank=True, null=True)),
                ('premios', models.TextField(blank=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='retos/soportes/')),
                ('criterios_evaluacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('consecutivo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'db_table': 'retos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='RetoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/soportes/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo de reto',
                'verbose_name_plural': 'Archivos de reto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/seguimientos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo de seguimiento',
                'verbose_name_plural': 'Archivos de seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('inicio', 'Inicio'), ('seguimiento', 'Seguimiento'), ('preseleccion', 'Preseleccion'), ('evaluacion', 'Evaluacion / reconocimiento'), ('otro', 'Otro')], default='seguimiento', max_length=30)),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.localdate)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('avances', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de reto',
                'verbose_name_plural': 'Seguimientos de retos',
                'ordering': ['-fecha_sesion', '-creado_en'],
            },
        ),
    ]
