# Generated by Django 6.0.6 on 2026-06-26 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reto', 'Reto'), ('hackathon', 'Hackathon')], default='reto', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('nivel_academico', models.CharField(blank=True, max_length=120)),
                ('fecha_inicio_tentativa', models.DateField(blank=True, null=True)),
                ('fecha_fin_tentativa', models.DateField(blank=True, null=True)),
                ('fecha_limite_postulacion', models.DateField(blank=True, null=True)),
                ('premios', models.TextField(blank=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='retos/soportes/')),
                ('criterios_evaluacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('consecutivo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='IntegracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(blank=True, max_length=140)),
                ('nivel_formacion', models.CharField(blank=True, max_length=120)),
                ('programa_academico', models.CharField(blank=True, max_length=160)),
                ('ecosistema', models.CharField(blank=True, max_length=140)),
                ('alcance', models.TextField(blank=True)),
                ('entregable_esperado', models.CharField(blank=True, max_length=180)),
                ('cronograma_sesiones', models.TextField(blank=True)),
                ('equipo_profesores', models.TextField(blank=True)),
                ('equipo_estudiantes', models.TextField(blank=True)),
                ('expertos_invitados', models.TextField(blank=True)),
                ('requerimientos_empresa', models.TextField(blank=True)),
                ('requerimientos_internos', models.TextField(blank=True)),
                ('espacio_fisico', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones_profesor', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Integracion academica',
                'verbose_name_plural': 'Integraciones academicas',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_retos', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Historial de estado de reto',
                'verbose_name_plural': 'Historial de estados de retos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('inicio', 'Inicio'), ('seguimiento', 'Seguimiento'), ('preseleccion', 'Preseleccion'), ('evaluacion', 'Evaluacion / reconocimiento'), ('otro', 'Otro')], default='seguimiento', max_length=30)),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.localdate)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('avances', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_retos', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Seguimiento de reto',
                'verbose_name_plural': 'Seguimientos de retos',
                'ordering': ['-fecha_sesion', '-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='reto',
            index=models.Index(fields=['empresa', 'estado'], name='retos_reto_empresa_fe1975_idx'),
        ),
        migrations.AddIndex(
            model_name='reto',
            index=models.Index(fields=['estado', 'fecha_limite_postulacion'], name='retos_reto_estado_dd5211_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionacademica',
            index=models.Index(fields=['profesor', 'estado'], name='retos_integ_profeso_190c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionacademica',
            index=models.Index(fields=['reto', 'estado'], name='retos_integ_reto_id_c04799_idx'),
        ),
    ]
