# Generated by Django 6.0.6 on 2026-07-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoreto',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_retos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadoreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='retos.reto'),
        ),
    ]
