# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoreto',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_retos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracionacademica',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracionacademica',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='historialestadoreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='seguimientoreto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_retos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimientoreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='seguimientoarchivo',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='retos.seguimientoreto'),
        ),
        migrations.AddIndex(
            model_name='integracionacademica',
            index=models.Index(fields=['profesor', 'estado'], name='retos_integ_profeso_190c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionacademica',
            index=models.Index(fields=['reto', 'estado'], name='retos_integ_reto_id_c04799_idx'),
        ),
    ]
