# Generated by Django 6.0.6 on 2026-07-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoreto',
            name='estado_nuevo',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En aprobacion'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='RetoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/soportes/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Archivo de reto',
                'verbose_name_plural': 'Archivos de reto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/seguimientos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='retos.seguimientoreto')),
            ],
            options={
                'verbose_name': 'Archivo de seguimiento',
                'verbose_name_plural': 'Archivos de seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
