# Generated by Django 6.0.6 on 2026-07-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/soportes/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Archivo de reto',
                'verbose_name_plural': 'Archivos de reto',
                'ordering': ['-creado_en'],
            },
        ),
    ]
