# Generated by Django 6.0.6 on 2026-07-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_retoarchivo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='integracionacademica',
            name='retos_integ_profeso_190c3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='integracionacademica',
            name='retos_integ_reto_id_c04799_idx',
        ),
        migrations.RemoveField(
            model_name='seguimientoreto',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='seguimientoreto',
            name='reto',
        ),
        migrations.RemoveField(
            model_name='integracionacademica',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='integracionacademica',
            name='reto',
        ),
        migrations.DeleteModel(
            name='SeguimientoArchivo',
        ),
        migrations.DeleteModel(
            name='SeguimientoReto',
        ),
        migrations.DeleteModel(
            name='IntegracionAcademica',
        ),
    ]
