# Generated by Django 6.0.6 on 2026-07-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_remove_integracionacademica_retos_integ_profeso_190c3b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='tiene_convenio_institucional',
            field=models.BooleanField(default=False),
        ),
    ]
