# Generated by Django 6.0.6 on 2026-08-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0005_reto_tiene_convenio_institucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRetoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='equipos_academicos_estudiante', to=settings.AUTH_USER_MODEL)),
                ('expertos_invitados', models.ManyToManyField(blank=True, related_name='equipos_academicos_experto', to=settings.AUTH_USER_MODEL)),
                ('profesores', models.ManyToManyField(blank=True, related_name='equipos_academicos_profesor', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_academicos', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Equipo de Reto Académico',
                'verbose_name_plural': 'Equipos de Reto Académico',
                'db_table': 'equipos_reto_academico',
            },
        ),
        migrations.CreateModel(
            name='IntegracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(blank=True, max_length=150)),
                ('programa', models.CharField(blank=True, max_length=150)),
                ('nivel_formacion', models.CharField(blank=True, max_length=100)),
                ('asignatura', models.CharField(blank=True, max_length=150)),
                ('alcance', models.TextField(blank=True, help_text='Definición del alcance académico del reto')),
                ('entregable_esperado', models.TextField(blank=True, help_text='Qué debe entregar exactamente el equipo de estudiantes')),
                ('reto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracion_academica', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Integración Académica',
                'verbose_name_plural': 'Integraciones Académicas',
                'db_table': 'integracion_academica',
            },
        ),
        migrations.CreateModel(
            name='SesionRetoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio'), ('seguimiento', 'Seguimiento'), ('preseleccion', 'Preselección'), ('evaluacion', 'Evaluación')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('enlace_reunion', models.URLField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_academicas', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Sesión Académica de Reto',
                'verbose_name_plural': 'Sesiones Académicas de Reto',
                'db_table': 'sesiones_reto_academico',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
