# Generated by Django 6.0.6 on 2026-08-03 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('retos', '0006_equiporetoacademico_integracionacademica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos', to='academico.facultad'),
        ),
        migrations.AddField(
            model_name='reto',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos', to='academico.programa'),
        ),
    ]
