# Generated by Django 6.0.6 on 2026-08-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('retos', '0007_reto_facultad_reto_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='ecosistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos', to='academico.ecosistema'),
        ),
    ]
