# Generated by Django 6.0.6 on 2026-08-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0008_reto_ecosistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegracionAcademica',
        ),
    ]
