# Generated by Django 6.0.6 on 2026-08-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participaciones', '0004_postulacion_habilidades_postulacion_programa_and_more'),
        ('retos', '0009_delete_integracionacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiporetoacademico',
            name='equipo_espejo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_academico', to='participaciones.equipo'),
        ),
    ]
