# Generated by Django 6.0.6 on 2026-08-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0010_equiporetoacademico_equipo_espejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='area',
            field=models.CharField(blank=True, choices=[('Tecnología', 'Tecnología'), ('Sostenibilidad', 'Sostenibilidad'), ('Emprendimiento', 'Emprendimiento'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Finanzas', 'Finanzas'), ('Mercadeo', 'Mercadeo'), ('Derecho', 'Derecho'), ('Educación', 'Educación'), ('Diseño y Creatividad', 'Diseño y Creatividad'), ('Otra', 'Otra')], max_length=120),
        ),
        migrations.AlterField(
            model_name='reto',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Educación Continua', 'Educación Continua')], max_length=120),
        ),
    ]
