# Generated by Django 6.0.6 on 2026-08-29 17:40

from django.db import migrations


def backfill_equipos_espejo(apps, schema_editor):
    """Crea el `Equipo` operativo espejo para cada equipo academico que aun no lo tiene.

    Los equipos academicos creados antes del puente `equipo_espejo` quedaron sin
    reflejo en `participaciones.Equipo`, que es el modelo al que apuntan los
    entregables y las votaciones de hackathon. Sin espejo, el desplegable de
    inscripcion a hackathon sale vacio. Reproduce la logica de
    `sincronizar_equipo_academico` usando modelos historicos.
    """
    EquipoRetoAcademico = apps.get_model('retos', 'EquipoRetoAcademico')
    Equipo = apps.get_model('participaciones', 'Equipo')
    MiembroEquipo = apps.get_model('participaciones', 'MiembroEquipo')

    for equipo_academico in EquipoRetoAcademico.objects.filter(equipo_espejo__isnull=True):
        equipo = Equipo.objects.create(
            reto_id=equipo_academico.reto_id,
            nombre=equipo_academico.nombre_equipo,
        )
        equipo_academico.equipo_espejo = equipo
        equipo_academico.save(update_fields=['equipo_espejo'])

        estudiantes = list(equipo_academico.estudiantes.order_by('pk'))
        for indice, estudiante in enumerate(estudiantes):
            MiembroEquipo.objects.create(
                equipo=equipo,
                estudiante_id=estudiante.pk,
                rol='LIDER' if indice == 0 else 'MIEMBRO',
            )


def reverse_backfill(apps, schema_editor):
    # Dejar los espejos creados es inofensivo y borrarlos podria destruir
    # datos de hackathon ya enlazados; el reverse se deja vacio a proposito.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0011_alter_reto_area_alter_reto_nivel_academico'),
        ('participaciones', '0004_postulacion_habilidades_postulacion_programa_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_equipos_espejo, reverse_backfill),
    ]
