# Generated by Django 6.0.6 on 2026-07-21 19:40

import apps.empresas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('sector_industrial', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('VERIFICADA', 'Verificada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('estado_listas_restrictivas', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'No aparece en listas'), ('RECHAZADO', 'Aparece en listas restrictivas')], default='PENDIENTE', max_length=20)),
                ('evidencia_listas', models.FileField(blank=True, null=True, upload_to='evidencias_listas/')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones_admin', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contacto de Empresa',
                'verbose_name_plural': 'Contactos de Empresa',
                'db_table': 'contactos_empresa',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CAMARA_COMERCIO', 'Camara de Comercio'), ('RUT', 'Registro Unico Tributario (RUT)'), ('CEDULA_REPRESENTANTE', 'Cedula del Representante Legal'), ('CONVENIO', 'Convenio Institucional')], max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.empresas.models.ruta_documentos_empresa)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADO', 'En Revision'), ('VERIFICADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=15)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Documento de Empresa',
                'verbose_name_plural': 'Documentos de Empresa',
                'db_table': 'documentos_empresas',
                'unique_together': {('empresa', 'tipo_documento')},
            },
        ),
    ]
