# Generated by Django 6.0.6 on 2026-07-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='renuncio_a_convenio',
            field=models.BooleanField(default=False),
        ),
    ]
