# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contactoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='documentoempresa',
            unique_together={('empresa', 'tipo_documento')},
        ),
    ]
