# Generated by Django 6.0.6 on 2026-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_verificada',
            field=models.BooleanField(default=False),
        ),
    ]
