# Generated by Django 6.0.6 on 2026-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_es_verificada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='es_verificada',
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('VERIFICADA', 'Verificada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observaciones_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
