# Generated by Django 6.0.6 on 2026-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_empresa_es_verificada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempresa',
            name='tipo_documento',
            field=models.CharField(choices=[('CAMARA_COMERCIO', 'Camara de Comercio'), ('RUT', 'Registro Unico Tributario (RUT)'), ('CEDULA_REPRESENTANTE', 'Cedula del Representante Legal'), ('CONVENIO', 'Convenio Institucional')], max_length=50),
        ),
    ]
