# Generated by Django 6.0.6 on 2026-07-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('empresas', '0005_alter_documentoempresa_tipo_documento'),
    ]

    operations = [
    ]
