# Generated by Django 6.0.6 on 2026-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.TextField(blank=True)),
                ('acta_url', models.FileField(blank=True, null=True, upload_to='actas_cierre/')),
                ('notas', models.TextField(blank=True)),
                ('catering', models.TextField(blank=True)),
                ('av_notas', models.TextField(blank=True)),
                ('invitados', models.TextField(blank=True)),
                ('espacio_notas', models.TextField(blank=True)),
                ('encuesta_enviada', models.BooleanField(default=False)),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cierre de Reto',
                'verbose_name_plural': 'Cierres de Reto',
                'db_table': 'cierres_reto',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinatario', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'db_table': 'reconocimientos',
            },
        ),
    ]
