# Generated by Django 6.0.6 on 2026-07-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cierre', '0001_initial'),
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrereto',
            name='cerrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierrereto',
            name='reto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cierre.cierrereto'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
