# Generated by Django 6.0.6 on 2026-08-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0002_initial'),
        ('retos', '0004_remove_integracionacademica_retos_integ_profeso_190c3b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrereto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AgendaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('espacio', models.CharField(blank=True, max_length=200)),
                ('recursos', models.TextField(blank=True)),
                ('invitados', models.TextField(blank=True)),
                ('agenda', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_cierre', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Agenda de cierre',
                'verbose_name_plural': 'Agendas de cierre',
            },
        ),
        migrations.CreateModel(
            name='EntregableFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('archivo', models.FileField(upload_to='cierres/entregables/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables_finales_cargados', to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables_finales', to='cierre.cierrereto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='cierre.cierrereto')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_satisfaccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cierre', 'participante')},
            },
        ),
    ]
