# Generated by Django 6.0.6 on 2026-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0003_cierrereto_actualizado_en_agendacierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrereto',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
