# Generated by Django 6.0.6 on 2026-08-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0004_alter_cierrereto_cerrado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrereto',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='cierrereto',
            name='av_notas',
        ),
        migrations.RemoveField(
            model_name='cierrereto',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='cierrereto',
            name='espacio_notas',
        ),
        migrations.RemoveField(
            model_name='cierrereto',
            name='invitados',
        ),
    ]
