# Generated by Django 6.0.6 on 2026-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LIDER', 'Lider'), ('MIEMBRO', 'Miembro')], default='MIEMBRO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
                'verbose_name_plural': 'Miembros de Equipo',
                'db_table': 'miembros_equipo',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobacion'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('RETIRADA', 'Retirada')], default='PENDIENTE', max_length=20)),
                ('motivacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulaciones',
            },
        ),
        migrations.CreateModel(
            name='RetoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reto Favorito',
                'verbose_name_plural': 'Retos Favoritos',
                'db_table': 'retos_favoritos',
            },
        ),
    ]
