# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participaciones', '0001_initial'),
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='miembroequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='participaciones.equipo'),
        ),
    ]
