# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participaciones', '0002_initial'),
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='retofavorito',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='retofavorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='miembroequipo',
            unique_together={('equipo', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('reto', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='retofavorito',
            unique_together={('usuario', 'reto')},
        ),
    ]
