# Generated by Django 6.0.6 on 2026-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participaciones', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='habilidades',
            field=models.TextField(blank=True, help_text='Habilidades y conocimientos relevantes'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='programa',
            field=models.CharField(blank=True, help_text='Programa academico del estudiante', max_length=150),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
