# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(blank=True, max_length=140)),
                ('nivel_formacion', models.CharField(blank=True, max_length=120)),
                ('programa_academico', models.CharField(blank=True, max_length=160)),
                ('ecosistema', models.CharField(blank=True, max_length=140)),
                ('alcance', models.TextField(blank=True)),
                ('entregable_esperado', models.CharField(blank=True, max_length=180)),
                ('cronograma_sesiones', models.TextField(blank=True)),
                ('equipo_profesores', models.TextField(blank=True)),
                ('equipo_estudiantes', models.TextField(blank=True)),
                ('expertos_invitados', models.TextField(blank=True)),
                ('requerimientos_empresa', models.TextField(blank=True)),
                ('requerimientos_internos', models.TextField(blank=True)),
                ('espacio_fisico', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integracion Academica',
                'verbose_name_plural': 'Integraciones Academicas',
                'db_table': 'integraciones_academicas',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(blank=True, max_length=30)),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.localdate)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('avances', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de Reto',
                'verbose_name_plural': 'Seguimientos de Reto',
                'db_table': 'seguimientos_reto',
            },
        ),
        migrations.CreateModel(
            name='SesionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio'), ('seguimiento', 'Seguimiento'), ('preseleccion', 'Preseleccion'), ('evaluacion', 'Evaluacion / Reconocimiento'), ('otro', 'Otro')], default='seguimiento', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('lugar', models.CharField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesion de Reto',
                'verbose_name_plural': 'Sesiones de Reto',
                'db_table': 'sesiones_reto',
            },
        ),
    ]
