# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retos', '0002_initial'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionacademica',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracionacademica',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones_seguimiento', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='seguimientoreto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimientoreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_seguimiento', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='sesionreto',
            name='integracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='seguimiento.integracionacademica'),
        ),
    ]
