# Generated by Django 6.0.6 on 2026-07-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoreto',
            name='tipo_sesion',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('seguimiento', 'Seguimiento'), ('preseleccion', 'Preseleccion'), ('evaluacion', 'Evaluacion / reconocimiento'), ('otro', 'Otro')], default='seguimiento', max_length=30),
        ),
        migrations.CreateModel(
            name='SeguimientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retos/seguimientos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='seguimiento.seguimientoreto')),
            ],
            options={
                'verbose_name': 'Archivo de seguimiento',
                'verbose_name_plural': 'Archivos de seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
