# Generated by Django 6.0.6 on 2026-07-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_remove_integracionacademica_retos_integ_profeso_190c3b_idx_and_more'),
        ('seguimiento', '0003_alter_seguimientoreto_tipo_sesion_seguimientoarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='retos.reto'),
        ),
    ]
