# Generated by Django 6.0.6 on 2026-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_alter_seguimientoreto_reto'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionacademica',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
