# Generated by Django 6.0.6 on 2026-08-27 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGIN_FALLIDO', 'Intento fallido de inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('CREACION', 'Creacion de usuario'), ('CAMBIO_ROL', 'Cambio de rol'), ('CAMBIO_ESTADO', 'Activacion o desactivacion'), ('IMPORTACION', 'Importacion masiva')], db_index=True, max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_registrada', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'db_table': 'log_actividad',
                'ordering': ['-creado_en'],
            },
        ),
    ]
