# Generated by Django 6.0.6 on 2026-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_logactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPRESA', 'Empresa'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('EXPERTO', 'Experto')], max_length=20),
        ),
    ]
