# Generated by Django 6.0.6 on 2026-06-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_empresa_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempresa',
            name='tipo_documento',
            field=models.CharField(choices=[('CAMARA_COMERCIO', 'Cámara de Comercio (No mayor a 30 días)'), ('RUT', 'Registro Único Tributario (RUT)'), ('CEDULA_REPRESENTANTE', 'Cédula del Representante Legal'), ('CONVENIO', 'Convenio Institucional / Prácticas')], max_length=50),
        ),
    ]
