# Generated by Django 6.0.6 on 2026-06-26 18:02

import apps.usuarios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol_perfilempresa_perfilestudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CAMARA_COMERCIO', 'Cámara de Comercio (No mayor a 30 días)'), ('RUT', 'Registro Único Tributario (RUT)'), ('CEDULA_REPRESENTANTE', 'Cédula del Representante Legal'), ('CONVENIO', 'Convenio Institucional / Prácticas')], max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.usuarios.models.ruta_documentos_empresa)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADO', 'En Revisión'), ('VERIFICADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_expedicion', models.DateField(blank=True, help_text='Fecha en que se emitió el documento', null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.perfilempresa')),
            ],
            options={
                'verbose_name': 'Documento de Empresa',
                'verbose_name_plural': 'Documentos de Empresa',
                'db_table': 'documentos_empresas',
                'unique_together': {('perfil_empresa', 'tipo_documento')},
            },
        ),
    ]
