# Generated by Django 6.0.6 on 2026-06-29 21:21

import apps.usuarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
        ('usuarios', '0003_alter_documentoempresa_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.usuarios.models.ruta_entregables_estudiante)),
                ('comentario_estudiante', models.TextField(blank=True, null=True)),
                ('comentario_profesor', models.TextField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('EN_REVISION', 'En Revisión'), ('CALIFICADO', 'Calificado')], default='ENVIADO', max_length=20)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'db_table': 'entregables_estudiantes',
                'unique_together': {('reto', 'estudiante')},
            },
        ),
    ]
