# Generated by Django 6.0.6 on 2026-06-29 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
        ('usuarios', '0004_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('ACEPTADA', 'Aceptada (Asignado)'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Postulación a Reto',
                'verbose_name_plural': 'Postulaciones a Retos',
                'db_table': 'postulaciones_retos',
                'unique_together': {('reto', 'estudiante')},
            },
        ),
    ]
