# Generated by Django 6.0.6 on 2026-07-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='reto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='presupuesto.presupuesto'),
        ),
    ]
