# Generated by Django 6.0.6 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='alerta_80_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
