# Generated by Django 6.0.6 on 2026-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaHackaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscripcion', 'Inscripcion'), ('desarrollo', 'Desarrollo'), ('presentacion', 'Presentacion'), ('premiacion', 'Premiacion')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('inicia_en', models.DateTimeField(blank=True, null=True)),
                ('termina_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Etapa de Hackaton',
                'verbose_name_plural': 'Etapas de Hackaton',
                'db_table': 'etapas_hackaton',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('resultados_publicados', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hackathon',
                'verbose_name_plural': 'Hackathons',
                'db_table': 'hackathons',
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Jurado',
                'verbose_name_plural': 'Jurados',
                'db_table': 'jurados_hackaton',
            },
        ),
        migrations.CreateModel(
            name='VotacionHackaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Votacion Hackaton',
                'verbose_name_plural': 'Votaciones Hackaton',
                'db_table': 'votaciones_hackaton',
            },
        ),
    ]
