# Generated by Django 6.0.6 on 2026-07-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackaton', '0001_initial'),
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='reto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='etapahackaton',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='hackaton.hackathon'),
        ),
        migrations.AddField(
            model_name='jurado',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='hackaton.hackathon'),
        ),
    ]
