# Generated by Django 6.0.6 on 2026-07-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackaton', '0002_initial'),
        ('participaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jurado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votacionhackaton',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='participaciones.equipo'),
        ),
        migrations.AddField(
            model_name='votacionhackaton',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='hackaton.hackathon'),
        ),
        migrations.AddField(
            model_name='votacionhackaton',
            name='jurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='hackaton.jurado'),
        ),
        migrations.AlterUniqueTogether(
            name='votacionhackaton',
            unique_together={('jurado', 'equipo')},
        ),
    ]
