# Generated by Django 6.0.6 on 2026-08-27 00:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0003_initial'),
        ('participaciones', '0004_postulacion_habilidades_postulacion_programa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacionhackaton',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
        migrations.CreateModel(
            name='InscripcionHackaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_hackaton', to='participaciones.equipo')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='hackaton.hackathon')),
                ('inscrito_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_hackaton', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripcion a Hackaton',
                'verbose_name_plural': 'Inscripciones a Hackaton',
                'db_table': 'inscripciones_hackaton',
                'ordering': ['-creado_en'],
                'unique_together': {('hackathon', 'equipo')},
            },
        ),
    ]
