# Generated by Django 6.0.6 on 2026-07-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('retos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregable',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='retos.reto'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='entregable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluacion.entregable'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entregable',
            unique_together={('reto', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('entregable', 'profesor')},
        ),
    ]
