# Generated by Django 6.0.6 on 2026-08-11 05:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_initial'),
        ('participaciones', '0003_initial'),
        ('retos', '0004_remove_integracionacademica_retos_integ_profeso_190c3b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='participaciones.equipo'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='es_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregable',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='entregable',
            name='titulo',
            field=models.CharField(default='Entregable del reto', max_length=180),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ComentarioEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_entregables', to=settings.AUTH_USER_MODEL)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_comentarios', to='evaluacion.entregable')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubricas_creadas', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='retos.reto')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('reto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='evaluacion.rubrica')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='evaluacion.rubrica'),
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntajes', to='evaluacion.criteriorubrica')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_criterio', to='evaluacion.evaluacion')),
            ],
            options={
                'unique_together': {('evaluacion', 'criterio')},
            },
        ),
    ]
