# Generated by Django 6.0.6 on 2026-08-11 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_entregable_equipo_entregable_es_final_and_more'),
        ('retos', '0004_remove_integracionacademica_retos_integ_profeso_190c3b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entregable',
            unique_together={('reto', 'estudiante', 'titulo')},
        ),
    ]
