# Generated by Django 6.0.6 on 2026-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_entregable_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
